server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true # in prod environment, set to false
  api-docs:
    path: /v3/api-docs
    enabled: true # in prod environment, set to false

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/devicesdb}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql