server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true # in prod environment, set to false
  api-docs:
    path: /v3/api-docs
    enabled: true # in prod environment, set to false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devicedb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:init.sql