spring:
    datasource:
        url: jdbc:tc:postgresql:14.4:///testdb
        username: test
        password: test
        driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    sql:
      init:
        mode: always
        schema-locations:
          - classpath:init.sql
          - classpath:test-data.sql