server:
  port: 8081
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true # in prod environment, set to false
  api-docs:
    path: /v3/api-docs
    enabled: true # in prod environment, set to false